version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 22
    commands:
      - npm ci
  build:
    commands:
      - npm run typecheck
      - npm test
      - npm run build:frontend
      - npm run cdk -- deploy --all --require-approval never

cache:
  paths:
    - '/root/.npm/**/*'